name: memory_gem
description: "A new Flutter project."
publish_to: 'none' # Remove this if you publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core UI & state
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  flutter_animate: ^4.2.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  provider: ^6.1.2

  # Localization
  easy_localization: ^3.0.0
  intl: ^0.20.2

  # ─── Firebase ────────────────────────────────────────────
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.2.0

dependency_overrides:
  # Match the actual web versions
  firebase_core_web: ^2.22.0
  firebase_auth_web: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
